version: 2

build:
   os: ubuntu-24.04
   tools:
      python: "3.12"

submodules:
   include: all

sphinx:
   # Path to the shared conf.py file.
   configuration: doc/conf.py

python:
   install:
   - requirements: requirements-readthedocs.txt
