
checks:
    python:
        basic_assert_on_tuple: true
        basic_dangerous_default_value: true
        basic_duplicate_key: true
        basic_empty_docstring: true
        basic_eval_used: true
        basic_exec_used: true
        basic_expression_not_assigned: true
        basic_function_redefined: true
        basic_init_is_generator: true
        basic_invalid_name:
            arguments: '[a-z_][a-z0-9_]{2,30}$'
            attributes: '[a-z_][a-z0-9_]{2,30}$'
            class_attributes: '([A-Za-z_][A-Za-z0-9_]{2,30}|(__.*__))$'
            classes: '[A-Z_][a-zA-Z0-9]+$'
            constants: '(([A-Z_][A-Z0-9_]*)|(__.*__))$'
            functions: '[a-z_][a-z0-9_]{2,30}$'
            inline_vars: '[A-Za-z_][A-Za-z0-9_]*$'
            methods: '[a-z_][a-z0-9_]{2,30}$'
            modules: '(([a-z_][a-z0-9_]*)|([A-Z][a-zA-Z0-9]+))$'
            variables: '[a-z_][a-z0-9_]{2,30}$'
            whitelisted_names: 'i,j,k,u,v,x,ex,it,ch,Run,_,__'
        basic_lost_exception: true
        basic_missing_docstring: true
        basic_old_raise_syntax: true
        basic_pointless_statement: true
        basic_pointless_string_statement: true
        basic_return_in_init: true
        basic_unnecessary_lambda: true
        basic_unnecessary_pass: true
        basic_unreachable: true
        basic_useless_else_on_loop: true
        classes_arguments_differ: true
        classes_attribute_defined_outside_init: true
        classes_bad_classmethod_argument: true
        classes_bad_context_manager: true
        classes_bad_mcs_classmethod_argument: true
        classes_bad_mcs_method_argument: true
        classes_bad_staticmethod_argument: true
        classes_interface_is_not_class: true
        classes_method_hidden: true
        classes_missing_interface_method: true
        classes_no_method_argument: true
        classes_non_iterator_returned: true
        classes_non_parent_init_called: true
        classes_no_self_argument: true
        classes_no_self_use: true
        classes_protected_access: true
        classes_signature_differs: true
        classes_super_init_not_called: true
        classes_valid_slots: true
        code_rating: true
        design_abstract_class_not_used: true
        design_interface_not_implemented: true
        duplicate_code: true
        exceptions_bad_except_order: true
        exceptions_bare_except: true
        exceptions_binary_op_exception: true
        exceptions_broad_except: true
        exceptions_catching_non_exception: true
        exceptions_notimplemented_raised: true
        exceptions_pointless_except: true
        exceptions_raising_bad_type: true
        exceptions_raising_non_exception: true
        exceptions_raising_string: true
        format_backtick: true
        format_bad_indentation:
            indentation: '4 spaces'
        format_bad_whitespace: true
        format_line_too_long:
            max_length: '120'
        format_lowercase_l_suffix: true
        format_missing_final_newline: true
        format_mixed_indentation: true
        format_old_ne_operator: true
        format_superfluous_parens: true
        format_trailing_whitespace: true
        format_unnecessary_semicolon: true
        imports_cyclic_import: true
        imports_deprecated_module: true
        imports_import_error: true
        imports_import_self: true
        imports_reimported: true
        imports_wildcard_import: true
        logging_not_lazy: true
        miscellaneous_fixme: true
        newstyle_bad_super_call: true
        string_bad_format_string_key: true
        string_bad_str_strip_call: true
        string_mixed_format_string: true
        typecheck_assignment_from_none: true
        typecheck_assignment_from_no_return: true
        variables_global_at_module_level: true
        variables_global_variable_not_assigned: true
        variables_global_variable_undefined: true
        variables_invalid_all_object: true
        variables_no_name_in_module: true
        variables_redefined_builtin: true
        variables_redefined_outer_name: true
        variables_redefine_in_handler: true
        variables_undefined_all_variable: true
        variables_undefined_loop_variable: true
        variables_unpacking_non_sequence: true
        variables_unused_argument: true
        variables_unused_import: true
        variables_unused_variable: true
        variables_unused_wildcard_import: true
        variables_used_before_assignment: true

