# pytest.ini (or tox.ini / setup.cfg)
[pytest]
; python_files=test_*.py
addopts = -p no:warnings
# collect any class named Test* (you can change the pattern if you like)
python_classes = Test*
# disable function/method collection entirely
python_functions = 
