ignore: {% set data = load_setup_py_data() %}
ignore: {% set version = data['version'] %}

package:
  name: orange3
  version: {{ data['version'] }}

source:
  git_url: ../

build:
  number: 0
  entry_points:
    - orange-canvas = Orange.canvas.__main__:main

  osx_is_app: True

  script:
    - python setup.py build -j1 bdist_wheel
    - if errorlevel 1 exit 1        # [win]
    - pip install --no-deps --no-cache --no-index -f dist Orange3=={{ version }}
    - if errorlevel 1 exit 1        # [win]

requirements:
  build:
    - python
    - setuptools
    # https://github.com/numpy/numpy/pull/6470
    - numpy         !=1.9.2   # [win]
    - numpy         >=1.9.0   # [not win]
    - pip           >=8
    - wheel

  run:
    - python
    - setuptools
    - numpy         >=1.16.0
    - scipy
    - scikit-learn  >=0.22
    - bottleneck    >=1.0.0
    - chardet       >=3.0.2
    - docutils
    - xlrd          >=0.9.2
    - keyring
    - keyrings.alt  # for alternative keyring implementations
    - pyqt
    - pyqtgraph     =0.10.0
    - anyqt         >=0.0.8
    - joblib
    - python.app    # [osx]
    - commonmark
    - serverfiles
    - matplotlib    >=2.0.0
    - opentsne      >=0.3.11
    - pandas
    - pyyaml
    - orange-canvas-core  >=0.1.9
    - orange-widget-base  >=4.4.0
    - openpyxl
    - python-louvain      >=0.13
    - xlsxwriter

test:
  # Python imports
  imports:
    - Orange
    - Orange.canvas.config

    - Orange.widgets
    - Orange.widgets.data
    - Orange.widgets.evaluate
    - Orange.widgets.model
    - Orange.widgets.unsupervised
    - Orange.widgets.visualize

    - Orange.classification
    - Orange.clustering
    - Orange.data
    - Orange.distance
    - Orange.evaluation
    - Orange.modelling
    - Orange.preprocess
    - Orange.projection
    - Orange.regression
    - Orange.statistics

  commands:
    - python -m unittest -v Orange.tests
    - orange-canvas --help

app:
  entry: orange-canvas
  summary: 'data visualization and data analysis tool'
  icon: ../distribute/icon-48.png

about:
  home: http://orange.biolab.si/
  license: GNU General Public License v3 or later (GPLv3+)
  summary: 'Orange, a component-based data mining framework.'
