package:
  name: orange3
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: ../

build:
  number: 0
  entry_points:
    - orange-canvas = Orange.canvas.__main__:main

  osx_is_app: True

  script:
    - python -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - numpy
    - recommonmark
    - setuptools
    - sphinx >=4.2.0,<8
    - wheel
    - trubar
  run:
    - python
    # GUI requirements
    - orange-canvas-core >=0.2.5,<0.3a
    - orange-widget-base >=4.25.0
    - anyqt >=0.2.0
    - pyqt >=5.12,!=5.15.1,<6.0
    - matplotlib-base >=3.2.0
    - pygments >=2.8.0
    - pyqtgraph >=0.13.1
    - qtconsole >=4.7.2
    # core requirements
    - baycomp >=1.0.2
    - bottleneck >=1.3.4
    - catboost >=1.0.1
    - chardet >=3.0.2
    - httpx >=0.21
    - joblib >=1.2.0
    - keyring
    - keyrings.alt
    - networkx
    - numpy >=1.20.0,<2
    - openpyxl >=3.1.3
    - openTSNE >=0.6.1,!=0.7.0
    - pandas >=1.4.0,!=1.5.0,!=2.0.0
    - packaging
    - pip >=19.3
    - python.app  # [osx]
    - python-louvain >=0.13
    - pyyaml
    - requests
    - scikit-learn >=1.5.1
    - scipy >=1.9
    - serverfiles
    - xgboost >=1.7.4,<2.1
    - xlsxwriter
    - xlrd >=1.2.0

test:
  # Python imports
  imports:
    - Orange
    - Orange.canvas.config

    - Orange.widgets
    - Orange.widgets.data
    - Orange.widgets.evaluate
    - Orange.widgets.model
    - Orange.widgets.unsupervised
    - Orange.widgets.visualize

    - Orange.classification
    - Orange.clustering
    - Orange.data
    - Orange.distance
    - Orange.evaluation
    - Orange.modelling
    - Orange.preprocess
    - Orange.projection
    - Orange.regression
    - Orange.statistics

  commands:
    - python -m unittest -v Orange.tests Orange.widgets.tests
    - orange-canvas --help

app:
  entry: orange-canvas
  summary: 'data visualization and data analysis tool'
  icon: ../distribute/icon-48.png

about:
  home: http://orange.biolab.si/
  license: GNU General Public License v3 or later (GPLv3+)
  summary: 'Orange, a component-based data mining framework.'
