#!/usr/bin/env bash
# Copyright (C) 2016 Kernc, Google Inc., authors, and contributors
# Licensed under http://www.apache.org/licenses/LICENSE-2.0
# Created By: miha@reciprocitylabs.com

set -o pipefail
set -o nounset
set -o errexit

ARG1=${1:-}
GIT_REPO="$(pwd)"
TMP_REPO="$(mktemp -d pylint_diff.XXXXXXX)"
SCRIPT=$(basename "$0")
PYLINT="$(command -v pylint 2>/dev/null || true)"
RADON="$(command -v radon 2>/dev/null || true)"
RADON_ARGS='cc --min C --no-assert --show-closures --show-complexity --average'

trap 'status=$?; cd '$GIT_REPO'; rm -rf '$TMP_REPO'; exit $status' EXIT


print_help ()
{
    echo "
Usage: $SCRIPT [TEST_COMMIT | -h]

This script will compare pylint error count from two different commits.
Note: all changes that are not committed will be ignored.

The script will work only if the current commit is a merge commit, or if the
second test_commit argument is provided.

Given the commit tree:

       D---E---F---G---H
            \\         /
             A---B---C

- Running '$SCRIPT' on H will check the diff between G and H.
- Running '$SCRIPT F' on H will check the diff between F and H.
- Running '$SCRIPT F' on C will check the diff between E and C. The E commit is
  set by the merge base of the current head and the specified commit F.
"
    exit 0
}

case $ARG1 in -h|--help) print_help ; esac

if [ ! "$PYLINT" ]; then
    echo 'Error: pylint is required'
    exit 3
fi

# Make a local clone: prevents copying of objects
# Handle shallow git clones
is_shallow=$([ -f "$GIT_REPO/.git/shallow" ] && echo true || echo)
if [ "$is_shallow" ]; then
    mv "$GIT_REPO/.git/shallow" "$GIT_REPO/.git/shallow-bak"
fi
git clone -q --local --depth=50 "$GIT_REPO" "$TMP_REPO"  2>/dev/null
if [ "$is_shallow" ]; then
    mv "$GIT_REPO/.git/shallow-bak" "$GIT_REPO/.git/shallow"
    cp "$GIT_REPO/.git/shallow" "$TMP_REPO/.git/shallow"
fi

cd "$TMP_REPO"
git reset --hard -q HEAD

CURRENT_COMMIT=$(git rev-parse HEAD)
if [ "$ARG1"  ]; then
    PREVIOUS_COMMIT=$(git merge-base HEAD "$ARG1")
else
    PREVIOUS_COMMIT=$(git show --pretty=raw HEAD |
                      awk '/^parent /{ print $2; exit }')
fi

echo "Comparing commits $CURRENT_COMMIT and $PREVIOUS_COMMIT ."

CHANGED_FILES=$(git diff --name-only $CURRENT_COMMIT $PREVIOUS_COMMIT |
                grep "\.py$" || true )
if [ ! "$CHANGED_FILES" ]; then
    echo "No python files changed. Skipping lint checks."
    exit 0
fi

echo
echo "Comparing files"
echo "==============="
echo "$CHANGED_FILES"
echo

# Run pylint on the old and new code, to compare the quality.
# If pylint is run multiple times it will store the previous results and show
# the change in quality with a non-negative number if code was improved or not
# changed, and a negative number if more code issues have been introduced.

checkout ()
{
    { git checkout -q "$1"
      git clean -xdfq
      git reset --hard -q HEAD
    } 2>/dev/null
}

Number_of_issues ()
{
    score_only="${1:-}"
    echo "$CHANGED_FILES" |
        xargs "$PYLINT" |
        { [ "$score_only" ] &&
          awk -F'[\\. ]' '/^Your code has been rated at /{ print $7 }' ||
          cat; } ||
        true
}

Cyclomatic_complexity ()
{
    score_only="${1:-}"
    echo "$CHANGED_FILES" |
        xargs "$RADON" $RADON_ARGS |
        { [ "$score_only" ] &&
          awk '/^Average complexity: /{ gsub(/[\(\)]/, ""); print $NF }' ||
          cat; } ||
        true
}


for check in \
    "Pylint Number_of_issues" \
    "radon Cyclomatic_complexity"
do
    func=${check#* }
    check=${check% *}
    if [ ! "$(eval echo \$$(echo $check | tr '[:lower:]' '[:upper:]') )" ]; then
        continue
    fi

    checkout $CURRENT_COMMIT
    RESULT_CURRENT=$($func score)
    checkout $PREVIOUS_COMMIT
    RESULT_PARENT=$($func score)
    checkout $CURRENT_COMMIT
    $func

    echo
    echo "$check results"
    echo "================================================================="
    echo "${func//_/ } on parent commit: $RESULT_PARENT"
    echo "${func//_/ } on the pull request: $RESULT_CURRENT"
    echo

    if [ $(echo "${RESULT_CURRENT:-0} > ${RESULT_PARENT:-0}" | bc) -eq 1 ]; then
        echo "FAIL: ${func//_/ } got worse"
        exit 1
    fi
done

echo "OK"
