#!/usr/bin/env bash
# Copyright (C) 2016 Google Inc., authors, and contributors <see AUTHORS file>
# Licensed under http://www.apache.org/licenses/LICENSE-2.0 <see LICENSE file>
# Created By: miha@reciprocitylabs.com
# Maintained By: miha@reciprocitylabs.com

set -o nounset
set -o errexit

ARG1=${1:-}
TMP_REPO=".temp_repo"
SCRIPT=$(basename "$0")
SCRIPTPATH=$( cd "$(dirname "$0")" ; pwd -P )
EVALUATION="error+warning+refactor+convention"

cd "${SCRIPTPATH}/.."


function print_help {
  echo "
Usage: $SCRIPT [test_commit] [-h]

This script will compare pylint error count from two different commits.
Note: all changes that are not committed will be ignored.

The script will work only if the current commit is a merge commit, or if the
second test_commit argument is provided.

Given the commit tree:

       D---E---F---G---H
            \\         /
             A---B---C

- Running '$SCRIPT' on H will check the diff between G and H.
- Running '$SCRIPT F' on H will check the diff between F and H.
- Running '$SCRIPT F' on C will check the diff between E and C. The E commit is
  set by the merge base of the current head and the specified commit F.
"
  exit 0
}


if [[ "$ARG1" == "-h" || "$ARG1" == "--help" ]]; then
    print_help
fi

rm -rf $TMP_REPO
mkdir -p $TMP_REPO
cp -a .git $TMP_REPO/
cd $TMP_REPO
git reset --hard HEAD

PARENT_1=$(git show --pretty=raw HEAD | grep "^parent" | head -1 | grep -oE "[^ ]*$")
PARENT_2=$(git show --pretty=raw HEAD | grep "^parent" | tail -1 | grep -oE "[^ ]*$")

CURRENT_COMMIT=$(git rev-parse HEAD)
if [[ "PARENT_1" != "PARENT_2" ]]; then
    # Running the script on a merge commit:
    # Checking First and second commit on this branch
    PREVIOUS_COMMIT=$PARENT_1
elif [[ "$ARG1" != ""  ]]; then
    PREVIOUS_COMMIT=$(git merge-base HEAD "$ARG1")
else
    print_help
fi



echo "Comparing commits $CURRENT_COMMIT and $PREVIOUS_COMMIT ."

CHANGED_FILES=$(git diff --name-only $CURRENT_COMMIT $PREVIOUS_COMMIT | grep "\.py$" || true )
if [[ "$CHANGED_FILES" == "" ]]; then
  echo "No python files changed. Skipping flake checks"
  cd "${SCRIPTPATH}/.."
  rm -rf $TMP_REPO
  exit 0
fi

echo "Checking files:"
echo "$CHANGED_FILES"
echo ""

# Run pylint on the old and new code, to compare the quality.
# If pylint is run multiple times it will store the previous results and show
# the change in quality with a non-negative number if code was improved or not
# changed, and a negative number if more code issues have been introduced.

function run_pylint() {
  
  result=$(echo "$CHANGED_FILES" | xargs pylint --evaluation=$EVALUATION 2> /dev/null | tail -n2 | \
    grep -E " [^ ]+/10" -o | head -n1 | grep -E -e "[^\.]+" -o | head -n1 \
    || true )

  if [[ "$result" != "" ]]; then
    echo $result
  else
    echo "0"
  fi
}

git checkout -q $CURRENT_COMMIT
git clean -xdfq
git reset --hard HEAD
echo "Running pylint on current commit."
RESULT_CURRENT=$( run_pylint )

git checkout -q $PREVIOUS_COMMIT
git clean -xdfq
git reset --hard HEAD
echo "Running pylint on parent commit."
RESULT_PARENT=$( run_pylint )

echo "
-------------------------------------------------------------------------------
"
echo "$CHANGED_FILES" | xargs pylint || true
echo "
-------------------------------------------------------------------------------
"

cd "${SCRIPTPATH}/.."
rm -rf $TMP_REPO

echo "Pylint results."
echo "Number of issues on parent commit: $RESULT_PARENT"
echo "Number of issues on the pull request: $RESULT_CURRENT"

if [ "$RESULT_CURRENT" -le "$RESULT_PARENT" ]; then
  echo "Ok"
  exit 0
else
  echo "FAIL: pylint score got worse"
  exit 1
fi
